on:
  push:
  workflow_dispatch:
  # Run every 3 hours at 15 minutes past the hour
  # schedule: [{cron: '15 0/3 * * *'}]

name: render

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
    - uses: r-lib/actions/setup-r-dependencies@v2

    - name: Render R Markdown
      run: Rscript -e "rmarkdown::render('render_diamonds.Rmd')"

    # Commit the rendered R Markdown to the repo
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Automated render of R Markdown document"
        file_pattern: render_diamonds.html
